language: php

php:
  - 5.6

matrix:
  include:
  - php: 5.6
    env: COMPOSER_FLAGS="--prefer-lowest"
  - php: 5.6
    env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
  - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
